### ISSUE TITLE
Add RHEL 7 support

### ISSUE THREAD

**Issue by makentenza** [redhat-sap/sap-hana-ha-pacemaker#5]
The role actually supports pacemaker setup for RHEL 8 servers. We need to add support for RHEL 7 as well.

**Comment by fdanapfel** [comment]
See Sections '4.5.1. RHEL 7.x'/'4.7.1 RHEL 7.x'  and '4.5.2. RHEL 8.x'/'4.7.2 RHEL 8.x'  in https://access.redhat.com/articles/3004101 for more info on the differences between RHEL7 and RHEL8.

**Comment by rhmk** [comment]
development moved to sap-linuxlab github org
