### ISSUE TITLE
Resource constraint commands failing

### ISSUE THREAD

**Issue by Axelay-Prime** [redhat-sap/sap-hana-ha-pacemaker#7]
This team set up the cluster before I arrived, and found that they had to run the role 2x because the first time all of the constraint steps failed.  It seems they were running before the resource creation step had completed.

The team here has worked around this by inserting 'sleep' commands between these steps.  (instead of running it 2x)  so I wanted to share their experiences here in case this resonates as a situation that warrants more discussion, or changes.

**Comment by rhmk** [comment]
The development moves to sap-linuxlab github org
